config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'

   resources :students 

  resources :completed_subjects, only: [] do
    resources :tests, only: [:new, :create]
  end

  resources :subjects do
    resources :completed_subjects, only: [:index, :new, :create]

  resources :questions do
    resources :answers do
    end
  end
  end
  # Add other routes as needed

  root 'subjects#index'


      
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/completed_subject.rb
class CompletedSubject < ApplicationRecord
  belongs_to :student
  belongs_to :subject
  has_many :tests
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject
  has_many :answers
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :completed_subjects
  has_many :tests, through: :completed_subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
   has_many :questions
   has_many :completed_subjects
end   

app/models/test.rb
  class Test < ApplicationRecord
    belongs_to :completed_subject
    has_and_belongs_to_many :questions
    validates :correct_percentage, presence: true
  end

app/models/test_question.rb
class TestQuestion < ApplicationRecord
  belongs_to :test
  belongs_to :question
  belongs_to :answer, optional: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    def index
        @answers = Answer.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        User.find_by(id: session[:user_id])
    end
end

app/controllers/completed_subjects_controller.rb
class CompletedSubjectsController < ApplicationController
  def new
    @subject = Subject.find(params[:subject_id])
    @completed_subject = CompletedSubject.new
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @completed_subject = @subject.completed_subjects.build(completed_subject_params)
    @completed_subject = CompletedSubject.new(completed_subject_params)
    if @completed_subject.save
      redirect_to subject_path(@completed_subject), notice: 'Completed subject was successfully created.'
    else
      render :new
    end
  end

  def index
    @completed_subjects = CompletedSubject.all
  end

  def show
    byebug
    @completed_subjects = CompletedSubject.find_by(id: params[:id])
  end

  private

  def completed_subject_params
    params.require(:completed_subject).permit(:student_id, :subject_id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_subject
  before_action :set_question, only: %i[show edit update destroy]

  def show; end

  def index
    @questions = Question.all
  end

  def new
    if params[:subject_id]
      @subject = Subject.find(params[:subject_id])
      @questions = @subject.questions.new
    else
      @services = Subject.all
    end
    @question = Question.new
  end

  def create
    @subject = Subject.find(params[:question][:subject_id])
    @question = @subject.questions.new(question_params)
    if @question.save
      redirect_to subject_question_path(@subject, @question), notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to subject_question_path(@subject, @question), notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to subject_path(@subject), notice: 'Question was successfully destroyed.'
  end

  private

  def set_subject
    @subject = Subject.find(params[:subject_id])
  end

  def set_question
    @question = @subject.questions.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # render login form
  end

  def create
    @student = Student.find_by_email(params[:email])

    if @student.present?
      if @student.password == params[:password]
        session[:student_id] = @student.id
        redirect_to subjects_path, notice: 'Loggded in successfully'
      end
    else
      flash[:error] = 'Invaild email or password_digest'
      redirect_to login_path
      # render :new, aler: "you con't update another Admins service."
    end
  end

  def destroy
    session.delete(:student_id)
    current_user = nil?
    redirect_to login_path, notice: 'Loggout successfully '
  end
end

app/controllers/students_controller.rb
# app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
    @subjects = Subject.all
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # app/controllers/subjects_controller.rb
  before_action :set_subject, only: %i[show edit update]

  def index
    @subjects = Subject.all
  end

  def show; end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to @subject, notice: 'Subject was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @subject.update(subject_params)
      redirect_to @subject, notice: 'Subject was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def new
    @subject = Subject.find_by_id(params[:subject_id])
    @subject_question = @subject.questions
    @completed_subjects = CompletedSubject.find(params[:completed_subject_id])
    @test = Test.new
  end

  def create
    @completed_subjects = CompletedSubject.find(params[:completed_subject_id])
    @subject = Subject.find_by_id(params[:subject_id])
    @subject_question = @subject.questions
    @test = Test.new(test_params)
    if @test.save
      redirect_to subject_completed_subject_tests_path, notice: 'Completed subject was successfully created.'
    else
      render :new
    end
  end

  def index
    @tests = Test.all
  end

  private

  def test_params
    params.require(:test).permit(:completed_subject_id, :totel_question, :correct_ans)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/answers/index.html.erb
<div class="table-wrapper">

<h1>All Reviews</h1>
<table class="fl-table">
  <thead>
    <tr>
      <th>question_id</th>
      <th>option</th>
      <th>correct option</th>

      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@answers.each do |question| %>
      <tr>
        <td><%= question.question_id%></td>
        <td><%= question.content %></td>
        <td><%= question.correct %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<br>

  <%= link_to "all quetion", subject_questions_path,class:"btn btn-outline-dark" %>

app/views/completed_subjects/index.html.erb
<h1>Subjects</h1>

<ul>
  <% @completed_subject.each do |subject| %>
    <li><%= link_to subject.name, new_user_subject_completed_subject_path(current_user, subject) %></li>
  <% end %>
</ul>

app/views/completed_subjects/new.html.erb
<!-- app/views/completed_subjects/new.html.erb -->
<%= form_with(model: [@student,@subject, @completed_subject], local: true) do |form| %>
    <%= form.hidden_field :subject_id, value: @subject.id %><br>
    <%= form.hidden_field :student_id, value: session[:student_id]%><br>
    <%= form.submit 'Create Completed Subject' %>
<% end %>

app/views/completed_subjects/show.html.erb
<!-- app/views/completed_subjects/show.html.erb -->
<h1>Completed Subject Details</h1>
<p><strong>Student:</strong> <%= @completed_subject.student.name %></p>
<p><strong>Subject:</strong> <%= @completed_subject.subject.name %></p>
<p><strong>Grade:</strong> <%= @completed_subject.grade %></p>
<!-- Add display for other attributes -->

app/views/questions/_form.html.erb
<div class="signin">
  <div class="content">
    <%= form_with(model: [@subject, @question],local: true) do |form| %>
<%= form.hidden_field :subject_id, value: @subject.id %><br>
<%= form.label :content %><br>
<%= form.text_field :content,class:"label1" %><br>

<%= form.submit "create question",class:"btn btn-outline-light" %>
<%= link_to "All subjects", subjects_path,class:"btn btn-outline-light" %>
<%= link_to "All question", subject_questions_path %>

<%end %>
</div>
</div>

app/views/questions/index.html.erb
<div class="table-wrapper">

<h1>All Reviews</h1>
<table class="fl-table">
  <thead>
    <tr>
      <th>question_id</th>
      <th>subject_id</th>
      <th>content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.subject_id%></td>
        <td><%= question.content %></td>
        <td><%= link_to "show option", subject_question_answers_path(question.subject_id,question.id),class:"btn btn-outline-dark" %> </td>

      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div class="f1">
  <%= link_to "New question", new_subject_question_path,class:"btn btn-outline-dark" %>
  <%= button_to "logout", logout_path, method: :delete,class:"btn btn-outline-dark"%>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>
<!-- <div class="table-wrapper"> -->
  <div>
    <% if @subject %>
  <h1 > create question for <%= @subject.name %></h1>
  <%= render 'form' %>
  <%else %>
  </div>
  <div class="table-wrapper">
  <h1> Select subject For question</h1>
  <ul>
  <div class="as">
    <%= link_to "All questions", subjects_path,class:"btn btn-outline-dark" %>
  </div>

</div>
  <%end %>

app/views/questions/show.html.erb
<div class="table-wrapper">
<table class="fl-table">
  <thead>
    <tr>
      <th>question_id     |</th>
       <th>subject_id      |</th>
      <th>content       |</th>
      <th>correct_option       |</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @question.id %></td>
        <td><%= @question.subject_id%></td>
        <td><%= @question.content %></td>
      </tr>
  </tbody>
</table>
<br>
<div class="form">
  <%= link_to "new question", new_subject_question_path %>||
  <%= link_to "All question", subject_questions_path %>
</div>
</div>
</div>

app/views/students/new.html.erb
<h1>Create a New Student</h1>

<%= form_with(model: @student, url: students_path, method: :post) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit 'Create Student' %>
  </div>
<% end %>

app/views/students/show.html.erb
<!-- app/views/students/show.html.erb -->
<h1>Student Details</h1>

<p><strong>Name:</strong> <%= @student.name %></p>
<p><strong>Email:</strong> <%= @student.email %></p>
<p><strong>Email:</strong> <%= @student.password %></p>

<h1>Subjects</h1>
<%= link_to 'Edit', edit_student_path(@student) %> 
<%= link_to 'Back', students_path %>
<%= link_to 'subjects', subjects_path(@student) %>
<%= link_to 'completed_subject', new_student_subject_completed_subject_path(@student)%>

    

app/views/subjects/_form.html.erb
<%= f_with(model: @subject, url: @subject.persisted? ? subject_path(@subject) : subjects_path, method: @subject.persisted? ? :patch : :post) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.submit 'Save' %>
    </div>
  <% end %>
  

app/views/subjects/edit.html.erb
<!-- app/views/subjects/edit.html.erb -->
<h1>Edit Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<!-- app/views/subjects/index.html.erb -->
<h1>Subjects</h1>

<ul>
  <% @subjects.each do |subject| %>
    <li><%= link_to subject.name, subject_path(subject) %></li>
  <% end %>
</ul>
<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<!-- app/views/subjects/new.html.erb -->
<h1>New Subject</h1>

<%= form_with(model: @subject, url: @subject.persisted? ? subject_path(@subject) : subjects_path, method: @subject.persisted? ? :patch : :post) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.submit 'Save' %>
    </div>
  <% end %>
  

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<!-- app/views/subjects/show.html.erb -->
<h1><%= @subject.name %></h1>
<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>
<td><%= link_to 'create question',  new_subject_question_path(@subject),class:"btn btn-outline-dark"%></td>
<%= link_to 'new  completed Subject',  new_subject_completed_subject_path(@subject) %>